replicaCount: 1

image:
  repository: 178795995292.dkr.ecr.us-west-2.amazonaws.com/django-k8s-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: false  

configMap:
  name: django-config
  data:
    POSTGRES_DB: "myproject"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    DB_HOST: "django-db-service"
    DB_PORT: "5432"
    DEBUG: "False"
    ALLOWED_HOSTS: "172.31.39.115,localhost"
    
config:
  SECRET_KEY: "django-insecure-u(qc9*j0w=ut5db3f#izfz_8szd7rruds!p8p5hgwz0in=+s7t"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,.eu-north-1.elb.amazonaws.com"
  POSTGRES_DB: "myproject"
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mypassword"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"


resources:
  requests:
    memory: "32Mi"
    cpu: "25m"
  limits:
    memory: "64Mi"
    cpu: "50m"

nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: false
  className: nginx
  host: ""
  path: /
  pathType: Prefix
  tls: false
