# k8s-manifests/django-secrets.yaml

# Цей файл створюйте вручну в кластері або через Jenkins
# НЕ додавайте в Git репозиторій з реальними секретами!

apiVersion: v1
kind: Secret
metadata:
  name: django-db-secret
  namespace: default
type: Opaque
data:
  # База даних пароль (base64 encoded)
  # Отримайте з AWS Secrets Manager:
  # aws secretsmanager get-secret-value --secret-id devops-final-dev-db-credentials --query SecretString --output text
  password: <BASE64_ENCODED_DB_PASSWORD>
  
  # Superuser пароль для Django (base64 encoded)
  superuser-password: YWRtaW4xMjM=  # admin123 (змініть на безпечний)

---
apiVersion: v1
kind: Secret
metadata:
  name: django-app-secret
  namespace: default
type: Opaque
data:
  # Django Secret Key (base64 encoded)
  # Генеруйте новий: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
  secret-key: <BASE64_ENCODED_DJANGO_SECRET_KEY>

---
# External Secret для автоматичної синхронізації з AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: django-db-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: django-db-secret
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: devops-final-dev-db-credentials
      property: password