apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
data:
  SECRET_KEY: "{{ .Values.config.SECRET_KEY }}"
  DEBUG: "{{ .Values.config.DEBUG }}"
  ALLOWED_HOSTS: "{{ .Values.config.ALLOWED_HOSTS }}"
  POSTGRES_DB: "{{ .Values.config.POSTGRES_DB }}"
  POSTGRES_USER: "{{ .Values.config.POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{ .Values.config.POSTGRES_PASSWORD }}"
  POSTGRES_HOST: "{{ .Values.config.POSTGRES_HOST }}"
  POSTGRES_PORT: "{{ .Values.config.POSTGRES_PORT }}"
