apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "django-app.fullname" . }}-sa
  labels:
    app: {{ include "django-app.name" . }}
    chart: {{ include "django-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::178795995292:role/django-k8s-cluster-node-group-role"